<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/NUMPY_RIVISION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
li = [1.0, 2,3,45]
arr = []
for num in li:
  arr.append(num)
print(arr)

[1.0, 2, 3, 45]


In [4]:
for nu in li:
  print(type(num))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [5]:
# 2d array using the 2d list
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 3D array using the 3d list
np.array([[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [7]:
# konse type ka array bna hai
a = np.array([[[1,2,3]]])
a.dtype

dtype('int64')

In [8]:
# Dimension check
a.ndim

3

In [9]:
np.zeros((4,5)) # tupe --> row,column


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((5,6)).dtype

dtype('float64')

In [26]:
np.ones(((5,5)) , dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [16]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.eye(3) # all diganol elements are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Arange function create an array in range (start , end , step)-->exclusive
# last value exclude in Arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(1,21).reshape(4,5)

# Reshape --> factors --> m*n --> total no. of elments

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
np.linspace(10,20,5) # linespace --> include first and last

array([10. , 12.5, 15. , 17.5, 20. ])

In [28]:
a = np.linspace(10,20,12)
b = np.linspace(30,40,12)

In [29]:
a+b

array([40.        , 41.81818182, 43.63636364, 45.45454545, 47.27272727,
       49.09090909, 50.90909091, 52.72727273, 54.54545455, 56.36363636,
       58.18181818, 60.        ])

In [30]:
c = np.array([1,2,3,4])
c**2

array([ 1,  4,  9, 16])

In [39]:
np.arange(20,100).reshape(16, 5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])