<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introduction of Numpy --->
# Numpy is an open-source library that is used for handle scintific calculations.

# Difference between List and Numpy --->
# (1). List Hetrogeneous data type and numpy is Homogenous data type
### ---> Heterogeneous ---> alag-alag type ke data ek saath rakh sakte ho.
### ---> Homogeneous ---> sirf ek hi type ke data ek saath rakh sakte ho.

# (2). List takes more memory as compare to Numpy
# (3). List takes more execution time as compare to numpy.

In [ ]:
# pip install numpy ---> for vs code
# !pip install numpy ---> for jupytor notebook
# uv add -r requrment.txt ---> for uv in vs code


In [3]:
import numpy as np

In [ ]:
a = [12,34,34]
type(a)

list

In [ ]:
b = np.array(a)
b

array([12, 34, 34])

In [ ]:
# User defined list

a = []
size = int(input("enter size: "))
for i in range(size):
    val = int(input("enter number: "))
    a.append(val)
print(a)


enter size: 2
enter number: 12
enter number: 23


array([12, 23])

In [ ]:
# user defind array
a = []
size = int(input("enter size: "))
for i in range(size):
    val = int(input("enter number: "))
    a.append(val)

b = np.array(a)
b

enter size: 2
enter number: 12
enter number: 34


array([12, 34])

In [ ]:
type (b)

numpy.ndarray

In [ ]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Matrix  ----> rows , columns

# row_1  = [1,2,3]
# row_2  = [4,5,6]
# row_3  = [7,8,9]

# col_1 = [1,4,7]
# col_2 = [2,5,8]
# col_3 = [3,6,9]

# total elements = row*coloumns = 3*3 = 9


In [ ]:
print("total rows and columns:", b.shape)
print("total elements:", b.size)

total rows and columns: (3, 3)
total elements: 9


In [ ]:
a = [[1,2,3,5], [6,4,5,6], [7,7,8,9]]
b = np.array(a)
b


array([[1, 2, 3, 5],
       [6, 4, 5, 6],
       [7, 7, 8, 9]])

In [ ]:
print("total rows and columns:", b.shape)
print("total elements:", b.size)

total rows and columns: (3, 4)
total elements: 12


In [ ]:
# How to check dimension of an matrix ?


In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a = np.array([[[1,2,3], [4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a.ndim

3

In [ ]:
# Images ---> Pixel(0,255) ---> Normalize(0,1) --> matrix ---> Operations
# DL (Deep Learning) ---> Artificial Neurons ---> weight ---> randomly creation ---> Numpy
# datasets ---> Dummy entry ---> random module  ---> attach pandas

In [ ]:
# pre_defined Functions in numpy

In [ ]:
# (1). Zeros() --> It will create an array in which all the values will be zero in either 1-d or multi_dimensional

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones() ---> It will create an arrat in which all the values will be one in either 1-0 ir multi-dimension

In [ ]:
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a = np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# (3). eye() ----> it will create an array in ehich digonal positional elements will be 1 and rest all are 0

In [3]:
a = np.eye(3)    ### ---> rows = coloumns  ---> symmetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
a = np.array(2,4) ### ---> rows != couloumns ---> aysymmetric matrix
a

TypeError: Cannot interpret '4' as a data type

In [ ]:
# (4), diag() ----> it will crate an array in which we can set our custom values at digonal position

In [9]:
a = np.diag([23,4,5,65])
a

array([[23,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 65]])

In [ ]:
# (5). Random module --->
# (a). randint() ---> it will create an array randomly in a given range.
# syntax : np.random.randint(min_range, max_range, total_numbers)

In [10]:
a = np.random.randint(1,10,3)
a

array([6, 1, 4])

In [ ]:
# (b). rand() ---> it will generate random numbers from 0-1.
# syntax : np.random.rand(total_random_numbers)

In [11]:
a = np.random.rand(3)
a

array([0.15998973, 0.11697266, 0.50664675])

In [ ]:
# (c).
# dataset (emp_data) (emp_id, salary, domain) ---> randomly coloumn add (working_hours)

In [ ]:
# (c). seed() --> it will fix or lock our generated data.
# syntax :
# np.random.seed(56)

In [22]:
np.random.seed(56)
a = np.random.randint(1,10,3)
a

array([86, 16, 65])

In [ ]:
# view and copy

In [23]:
a = np.array([12,34,34,343,434,34,45,34])
a

array([ 12,  34,  34, 343, 434,  34,  45,  34])

In [24]:
b = a[1:4]
b[:] = 0
b

array([0, 0, 0])

In [25]:
a

array([ 12,   0,   0,   0, 434,  34,  45,  34])

In [ ]:
# copy

In [28]:
a = np.array([12,34,34,343,434,34,45,34])
b = a[1:4].copy()
b[:] = 0
a

array([ 12,  34,  34, 343, 434,  34,  45,  34])

In [ ]:
# Reshaping the Array
# total rows * columns = total_elements

In [34]:
a = np.random.randint(1,50,12)
a

array([ 3, 11,  2, 17, 14, 21, 39, 45, 33,  9, 30, 31])

In [ ]:
# 1*12 , 12*1
# 3*4 , 4*3
# 6*2 , 2*6

In [35]:
a.reshape(2,6)

array([[ 3, 11,  2, 17, 14, 21],
       [39, 45, 33,  9, 30, 31]])

In [38]:
a.reshape(3,4)


array([[ 3, 11,  2, 17],
       [14, 21, 39, 45],
       [33,  9, 30, 31]])

In [ ]:
# y = mx + b
# m = matrix ---. weights
# x = values ---> matrix

# matrix(column) * (row)matrix

In [39]:
a.shape

(12,)

In [40]:
a.reshape(-1,3)

array([[ 3, 11,  2],
       [17, 14, 21],
       [39, 45, 33],
       [ 9, 30, 31]])

In [41]:
a.reshape(2,-1)

array([[ 3, 11,  2, 17, 14, 21],
       [39, 45, 33,  9, 30, 31]])

In [ ]:
# Oprations on Array

In [42]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [45]:
a+2

array([3, 4, 5, 6])

In [43]:
a*2

array([2, 4, 6, 8])

In [44]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [46]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [47]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [48]:
a + b

array([[ 6,  8],
       [10, 12]])

In [49]:
a - b

array([[-4, -4],
       [-4, -4]])

In [50]:
a * b

array([[ 5, 12],
       [21, 32]])

In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# 1*5 + 2*7  1*6+2*8

In [53]:
a.dot(b)  ### this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [56]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [58]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [59]:
b = a%2==0
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

In [60]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [61]:
a = np.arange(1,4)
a**3

array([ 1,  8, 27])

In [62]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.sum(a)

np.int64(45)

In [64]:
np.sum(a, axis = 1)   ### axis = 1 means row wise opration

array([ 6, 15, 24])

In [65]:
np.sum(a, axis = 0)   ### axis = 0 means column wise opration

array([12, 15, 18])

In [ ]:
# Unique() ---> it willl create an array in which it will remove duplicate values and it aill return 3 arrays :
# arr ---> Unique elements of array
# return_index = True ----> Indexing of unique elements
# return_counts = True ---> Frrequency of each unique element.


In [4]:
a = np.array([1,2,3,4,4,4,4,4,4,4,4,5,6,7,7,7,7,7,7,8])
a

array([1, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6, 7, 7, 7, 7, 7, 7, 8])

In [5]:
b = np.unique(a, return_index = True, return_counts = True)
b

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  1,  2,  3, 11, 12, 13, 19]),
 array([1, 1, 1, 8, 1, 1, 6, 1]))

In [ ]:
# linespace() ---> It will return an array in which elements will be same gap in a given range.
# syntax : np.linspace(min_range, max_range, total_elements)

In [6]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Horizontal And Vertical Stacking --->
# Horizontal Stacking ---> it will add 2 or more arrays in horizontaly

In [31]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [32]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [33]:
c = np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [36]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])