<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/NUMPY_PR_Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr + 4

array([5, 6, 7, 8])

In [4]:
arr * 4

array([ 4,  8, 12, 16])

In [7]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [8]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [13]:
a = np.arange(1,13).reshape(3,4) # Arange --> last value exclude

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr


array([1, 2, 3, 4])

In [14]:
a + arr

# Addition is performing on basis of axis = 0 it means all the elements of the
# Arrat is added with each row of the matrix

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [ ]:
# Broadcasting in numpy is a powerfull machanism that allows arithmetic opration
# on arrays of different shapes and size

# RULE
# (1) Dimension Compatibility
# the are qual size
# one of them has a size of 1

In [16]:
mat1 = np.arange(1,10).reshape(3,3)
mat2 = np.arange(10,19).reshape(3,3)

# According to the rule no 1 of the broadcasting the dimensions of both
# matrix have same dimensions
mat1 * mat2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [17]:
mat1 = np.arange(1,13).reshape(3,4)
arr = np.array([1,2,3])
arr1 = arr.reshape(3,1)

In [18]:
mat1 + arr1

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [22]:
# Q. (1) Create a 1D NumPy array containing numbers from 5 to 50 with a step of 5.
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
# Q. (2) Create a 2D array of shape (4, 3) filled with ones.
a = np.ones((4,3))
a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# Q. (3) Create an array of 6 equally spaced values between 0 and 1.
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
# Q. (4) Create a 3×3 identity matrix.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Q. (5) Find the shape, size, number of dimensions, and data type of a given array.
a = np.arange(1,13).reshape(3,4)
a.shape, a.size, a.ndim, a.dtype

((3, 4), 12, 2, dtype('int64'))

In [39]:
# Q. (6) Convert the Python list [10, 20, 30, 40, 50] into a NumPy array.
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [43]:
# Q. (7) Reshape a 1D array of 16 elements into a 4×4 matrix.
a = np.arange(1,17)
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
# Q. (8) Flatten a 2D array into 1D using both flatten() and ravel(). Observe the
# difference.
a = np.arange(1,7).reshape(2,3)
f = a.flatten()
r = a.ravel()
f[0] = 10
r[1] =20
print(f)
print(r)
print(a)

[10  2  3  4  5  6]
[ 1 20  3  4  5  6]
[[ 1 20  3]
 [ 4  5  6]]


In [54]:
# Q. (9) Access the middle element of a 1D array.
a = np.array([10, 20, 30, 40, 50])
a1 = a[len(a)//2]
a1

np.int64(30)

In [55]:
# Q. (10) Reverse a NumPy array without using loops.
a = np.array([1, 2, 3, 4, 5])
rev = a[::-1]
rev

array([5, 4, 3, 2, 1])

In [56]:
# 1. Extract all even-indexed elements
a = np.array([10, 20, 30, 40, 50, 60])
print(a[::2])

[10 30 50]


In [59]:
# 2. Extract the last column from a 2D array
a = np.arange(1,10).reshape(3,3)
print(a[:,-1])

[3 6 9]


In [60]:
# 3. Alternate elements starting from index 1
a = np.array([1, 2, 3, 4, 5, 6])
print(a[1::2])


[2 4 6]


In [61]:
# 4. Extract a 2×2 sub-matrix from a 3×3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[:2, :2])


[[1 2]
 [4 5]]


In [62]:
# 5. Print all elements except first and last
a = np.array([5, 10, 15, 20, 25])
print(a[1:-1])


[10 15 20]


In [63]:
# 1. Select all elements greater than 25
a = np.array([10, 20, 30, 40, 50])
print(a[a > 25])


[30 40 50]


In [64]:
# 2. Replace all negative values with 0

a = np.array([10, -5, 20, -3, 30])
a[a < 0] = 0
print(a)

[10  0 20  0 30]


In [66]:
# 3. Extract elements divisible by 3
a = np.array([3, 7, 9, 12, 15])
print(a[a % 3 == 0])

[ 3  9 12 15]


In [67]:
# 4. Count elements greater than mean
a = np.array([10, 20, 30, 40, 50])
print(np.sum(a > a.mean()))

2


In [68]:
# 5. Find indices where value is 50
a = np.array([10, 20, 50, 30, 50])
print(np.where(a == 50))

(array([2, 4]),)


In [69]:
# 1. Add two NumPy arrays element-wise

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [70]:
# 2. Matrix multiplication of two compatible matrices
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [72]:
# 3. Add scalar value 10 to every element
a = np.array([5, 10, 15])

r = a + 10
print(r)

[15 20 25]


In [73]:
# 4. Add (3,) array to (2,3) array using broadcasting
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b
print(result)

[[11 22 33]
 [14 25 36]]
