<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/NUMPY_RIVISION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# numpy ---> is a fundamental python library for numerical computing



In [ ]:
li = [1.0, 2,3,45]
arr = []
for num in li:
  arr.append(num)
print(arr)

[1.0, 2, 3, 45]


In [ ]:
for nu in li:
  print(type(num))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
# 2d array using the 2d list
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 3D array using the 3d list
np.array([[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# konse type ka array bna hai
a = np.array([[[1,2,3]]])
a.dtype

dtype('int64')

In [ ]:
# Dimension check
a.ndim

3

In [ ]:
np.zeros((4,5)) # tupe --> row,column


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,6)).dtype

dtype('float64')

In [ ]:
np.ones(((5,5)) , dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [ ]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.eye(3) # all diganol elements are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Arange function create an array in range (start , end , step)-->exclusive
# last value exclude in Arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,21).reshape(4,5)

# Reshape --> factors --> m*n --> total no. of elments

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.linspace(10,20,5) # linespace --> include first and last

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
a = np.linspace(10,20,12)
b = np.linspace(30,40,12)

In [ ]:
a+b

array([40.        , 41.81818182, 43.63636364, 45.45454545, 47.27272727,
       49.09090909, 50.90909091, 52.72727273, 54.54545455, 56.36363636,
       58.18181818, 60.        ])

In [ ]:
c = np.array([1,2,3,4])
c**2

array([ 1,  4,  9, 16])

In [ ]:
np.arange(20,100).reshape(16, 5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
# Created 1D array using the list comprehension
li = [i for i in range(1 , 101)]
np.array(li).reshape(10,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
# Matrix oprations
# what is matrix why use and ml matrix

In [2]:
import numpy as np

In [6]:
# Accessing the elements using the indices of the array in known indexing
# 0-Based indexing -> it the index should starts from 0
# array_name[index]
a = np.array([1,2,3,4,5])
# a[2]
# a[5-1]

# using the negative indexing we have accessed the last element from the array
# -1
a[-1]

np.int64(5)

In [7]:
# you have to print the numbers of array using the negative indexing [1,2,3,4,5]

In [13]:
a = np.array([1,2,3,4,5])
for i in range(-5,0):
    print(a[i])

1
2
3
4
5


In [9]:
# print all the elements into the reverse order using negative indexing

In [12]:
a = np.array([1,2,3,4,5])
for i in range(1 , len(a)+1):
   print(a[-i])

5
4
3
2
1


In [15]:
a = [1,2,3,4,5]

# Slicing is used to find or extract the subarray from the given array
# array_name[start_index , End_idx , step]

# By default the starting idx is 0
# by default the ending indexing len(array) -1
# step by default = 1

# a[1:4]
a[::2]

[1, 3, 5]

In [23]:
# Genrate an array using the arange function from 1 , 100 using 3 step print all the
# elements of the array

a = np.arange(1,101,3).reshape(1,34)
a

array([[  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
         40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
         79,  82,  85,  88,  91,  94,  97, 100]])

In [25]:
a = np.array([1,2,3,4,5])

# using slicing reversing the array
a[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
# Matirx indexing access

In [32]:
mtrx = np.arange(1,13).reshape(3,4)
print(mtrx[2][2])
# Matrix -> ([Rows],[Elements index])
mtrx[1]

11


array([5, 6, 7, 8])

In [33]:
# Print all the elements of the matrix

In [37]:
a = np.arange(1,13).reshape(3,4)
for i in a:
   for j in i:
      print(j , end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 