<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/NUMPY_RIVISION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
# numpy ---> is a fundamental python library for numerical computing



In [4]:
li = [1.0, 2,3,45]
arr = []
for num in li:
  arr.append(num)
print(arr)

[1.0, 2, 3, 45]


In [5]:
for nu in li:
  print(type(num))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [6]:
# 2d array using the 2d list
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 3D array using the 3d list
np.array([[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [8]:
# konse type ka array bna hai
a = np.array([[[1,2,3]]])
a.dtype

dtype('int64')

In [9]:
# Dimension check
a.ndim

3

In [10]:
np.zeros((4,5)) # tupe --> row,column


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.ones((5,6)).dtype

dtype('float64')

In [13]:
np.ones(((5,5)) , dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [14]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.eye(3) # all diganol elements are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Arange function create an array in range (start , end , step)-->exclusive
# last value exclude in Arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(1,21).reshape(4,5)

# Reshape --> factors --> m*n --> total no. of elments

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
np.linspace(10,20,5) # linespace --> include first and last

array([10. , 12.5, 15. , 17.5, 20. ])

In [19]:
a = np.linspace(10,20,12)
b = np.linspace(30,40,12)

In [20]:
a+b

array([40.        , 41.81818182, 43.63636364, 45.45454545, 47.27272727,
       49.09090909, 50.90909091, 52.72727273, 54.54545455, 56.36363636,
       58.18181818, 60.        ])

In [21]:
c = np.array([1,2,3,4])
c**2

array([ 1,  4,  9, 16])

In [22]:
np.arange(20,100).reshape(16, 5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [23]:
# Created 1D array using the list comprehension
li = [i for i in range(1 , 101)]
np.array(li).reshape(10,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
# Matrix oprations
# what is matrix why use and ml matrix

In [25]:
import numpy as np

In [26]:
# Accessing the elements using the indices of the array in known indexing
# 0-Based indexing -> it the index should starts from 0
# array_name[index]
a = np.array([1,2,3,4,5])
# a[2]
# a[5-1]

# using the negative indexing we have accessed the last element from the array
# -1
a[-1]

np.int64(5)

In [27]:
# you have to print the numbers of array using the negative indexing [1,2,3,4,5]

In [28]:
a = np.array([1,2,3,4,5])
for i in range(-5,0):
    print(a[i])

1
2
3
4
5


In [29]:
# print all the elements into the reverse order using negative indexing

In [30]:
a = np.array([1,2,3,4,5])
for i in range(1 , len(a)+1):
   print(a[-i])

5
4
3
2
1


In [31]:
a = [1,2,3,4,5]

# Slicing is used to find or extract the subarray from the given array
# array_name[start_index , End_idx , step]

# By default the starting idx is 0
# by default the ending indexing len(array) -1
# step by default = 1

# a[1:4]
a[::2]

[1, 3, 5]

In [32]:
# Genrate an array using the arange function from 1 , 100 using 3 step print all the
# elements of the array

a = np.arange(1,101,3).reshape(1,34)
a

array([[  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
         40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
         79,  82,  85,  88,  91,  94,  97, 100]])

In [33]:
a = np.array([1,2,3,4,5])

# using slicing reversing the array
a[::-1]

array([5, 4, 3, 2, 1])

In [34]:
# Matirx indexing access

In [35]:
mtrx = np.arange(1,13).reshape(3,4)
print(mtrx[2][2])
# Matrix -> ([Rows],[Elements index])
mtrx[1]

11


array([5, 6, 7, 8])

In [36]:
# Print all the elements of the matrix

In [37]:
a = np.arange(1,13).reshape(3,4)
for i in a:
   for j in i:
      print(j , end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [38]:
# Fancy indexing ---> is a technique in programming , especially in numpy , that
# allows you to select multiple elements from an array at once using a list or array of indices

In [41]:
a = np.random.randint(1,11,10)
a

array([4, 3, 8, 6, 3, 1, 6, 8, 1, 1])

In [44]:
# print(a[0])
indices = [1,4,8]
a1 = []
for i in indices:
   a1.append(a[i])

In [45]:
np.array(a1)

array([3, 3, 1])

In [48]:
# Here we're performing the fancy indexing
# We give the multiple indices of the elements whichever we want in list
a[[1,4,8]]


array([3, 3, 1])

In [54]:
# Arange --> last value exclude
arr = np.arange(1,11)
# here we are creating the view of the original array
view_arr = arr.view()
# here we are changing the first elements of the duplicated array

# view_arr[0] =  100
# view_arr

print(f'Original array : {arr}')
print(f'View : {view_arr}')

# View is a method which copies the refrence of the original object or
# arr . whenever we want to change anything into the duplicate array
# then it would effect on the original array

Original array : [ 1  2  3  4  5  6  7  8  9 10]
View : [ 1  2  3  4  5  6  7  8  9 10]


In [56]:
copy_arr = arr.copy()
print(copy_arr)

copy_arr[1] = 20
print(copy_arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 20  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# This copy() method is used to copy the object and create actual same

# Into this the original

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
np.where(arr>5) # Where ---> is a function for conditional selection and replacement

(array([5, 6, 7, 8, 9]),)

In [66]:
arr = np.arange(20,41)
# np.where function or method is used to find the indices on the basis of
# some conditions
np.where(arr > 25, 'High' , 'Low')

array(['Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High'], dtype='<U4')

In [72]:
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
arr2 = np.array([7,8,9])

# Vertical stacking is used to stack the array into the stack format vertically
np.vstack([arr , arr1 , arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.hstack([arr , arr1 , arr2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
matrix = np.arange(1 , 13).reshape(3,4)
arr = np.array([1,2,3]).reshape(3,1)
# np.hstack([matrix , arr])

print(matrix)
print('_____')

print(arr)

print(np.hstack([matrix , arr]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
_____
[[1]
 [2]
 [3]]
[[ 1  2  3  4  1]
 [ 5  6  7  8  2]
 [ 9 10 11 12  3]]


In [ ]:
# take an array ranging between 10 to 25
# 18 < child
# 18 > adult

In [71]:
a = np.arange(10 ,35)
np.where(a < 18 , 'Child' , 'Adult')

array(['Child', 'Child', 'Child', 'Child', 'Child', 'Child', 'Child',
       'Child', 'Adult', 'Adult', 'Adult', 'Adult', 'Adult', 'Adult',
       'Adult', 'Adult', 'Adult', 'Adult', 'Adult', 'Adult', 'Adult',
       'Adult', 'Adult', 'Adult', 'Adult'], dtype='<U5')