<a href="https://colab.research.google.com/github/krishkumawat0416-debug/PYTHON/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introduction to pandas --->
# Pandas is an open-source library of python which is used for handle data manipulation

In [1]:
import pandas as pd

In [ ]:
# Data structure of pandas:
# (1). series
# (2). Dataframe

In [ ]:
# (1). series ---> It is one-dimensional array it return only values not column name.


In [ ]:
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# type(a)

In [ ]:
# (2). DataFrame ---> It is multi-dimensional array and it returns values with column name.

In [ ]:
# Task ::: We have to create a dataframe of employees in which column are
# emo_id, emp_name, department, salary, working_hours

In [ ]:
a = {
    "emp_id": ['A101', "A102", 'A103'],
    "emp_name":['krish', 'rehan', 'abhishek'],
    "department":['it', 'it', 'op'],
    "salary":[20000, 23000, 45000],
    "working_hours":[6, 8, 10]
}


In [ ]:
df = pd.DataFrame(a)

In [ ]:
df

emp_id  emp_name department  salary  working_hours
0   A101     krish         it   20000              6
1   A102     rehan         it   23000              8
2   A103  abhishek         op   45000             10

In [ ]:
# How can we export our dataframe into csv data ?

In [ ]:
df.to_csv("emp_info.csv")  ### to_csv means export your data into csv file

In [ ]:
df.to_csv("new_emp_info.csv", index = False)  ## index = false means it willl remove unnamed column

In [ ]:
# How to import csv data using pandas

In [ ]:
df = pd.read_csv("/content/emp_info.csv")

In [ ]:
df

Unnamed: 0 emp_id  emp_name department  salary  working_hours
0           0   A101     krish         it   20000              6
1           1   A102     rehan         it   23000              8
2           2   A103  abhishek         op   45000             10

In [ ]:
df = pd.read_csv("/content/flipkart.csv")

In [ ]:
# df

In [ ]:
df = pd.read_csv("/content/MASURI PALSE.csv")

In [ ]:
# df


In [ ]:
# what is diffrence list and numpy ?
# how do we create a user defined array ?
# create an random array in range 100 to 200 and total values will be 64 and you have to reshape it all the possible factors ?
# create an array of (5,5) in which all the values will be 7 ?
# explain view vs copy with example ?
# diffrence between linspace() and unique() with code of example ?
# what is hstack() and vstack() ? create 4 arrays and connect it via  hstack, vstack. ?
# create an array in range 11-26 now you have to reshape it (4*4) and then you have to
# calculate total sum, row wise sum,  column wise sum

In [ ]:
list is a hetrogenous data type and numpy is a homogenous data type
list take more memory as compare numpy
list take more execution time as compare numpy

In [ ]:
a = []
size = int(input("enter your size : "))
for i in range(size):
    val = int(input("enter your value : "))
    a.append(val)
print(a);

enter your size : 4
enter your value : 12
enter your value : 2
enter your value : 34
enter your value : 45
[12, 2, 34, 45]


In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(100, 200, 64).reshape(4,16)
a

array([[141, 128, 100, 195, 107, 118, 174, 117, 139, 176, 148, 103, 189,
        166, 159, 139],
       [116, 103, 121, 107, 122, 182, 108, 115, 135, 198, 133, 181, 115,
        114, 122, 108],
       [101, 158, 196, 155, 121, 153, 183, 123, 190, 157, 179, 198, 139,
        147, 128, 159],
       [157, 132, 151, 131, 179, 140, 136, 157, 124, 124, 151, 150, 108,
        199, 165, 198]])

In [ ]:
a = np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
# view --> view is create a array you can change array element in use slicing then change array
# but change the original array in view

a = np.array([12,23,34,56,7,8,96,34,56])
b = a[5:9]
b[:] = 0
b

array([0, 0, 0, 0])

In [ ]:
# copy --> copy is create a array you can change array element in use slicing and change the element but not change
# the original array only change copy array
a = np.array([12,23,34,56,7,8,96,34,56])
b = a[5:9].copy()
b[:] = 0
b

array([0, 0, 0, 0])

In [ ]:
# linesapce --> is create a array in same gap of values
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# unique --> in create a array and remove duplicate and return 3 values
# arr --> reurn unique elememt
# return_index = true --> return indexing
# return_count = true --> return count

a = np.array([1,2,8,4,5,3,3,3,3,3,1,1,1,2,2,5,6,4,7,8])
a = (np.unique(a, return_index = True, return_counts = True))
a

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  1,  5,  3,  4, 16, 18,  2]),
 array([4, 3, 5, 2, 2, 1, 1, 2]))

In [ ]:
# what is hstack() and vstack() ? create 4 arrays and connect it via  hstack, vstack. ?
# hstack --> it will add 2 or more array

a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
c = np.arange(9,13).reshape(2,2)
c

array([[ 9, 10],
       [11, 12]])

In [ ]:
d = np.arange(13,17).reshape(2,2)
d

array([[13, 14],
       [15, 16]])

In [ ]:
np.hstack((a,b,c,d))

array([[ 1,  2,  5,  6,  9, 10, 13, 14],
       [ 3,  4,  7,  8, 11, 12, 15, 16]])

In [ ]:
# vstack --> it will Add 2 or more array
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)
d = np.arange(13,17).reshape(2,2)

np.vstack((a,b,c,d))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
# create an array in range 11-26 now you have to reshape it (4*4) and then you have to
# calculate total sum, row wise sum,  column wise sum

a = np.arange(11,27).reshape(4,4)
print(a.sum(axis = 0))

[68 72 76 80]


In [ ]:
a = np.arange(11,27).reshape(4*4)
print(a.sum(axis = 1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head()

In [6]:
df.head(3)
df.tail(5)

In [8]:
df.describe()

In [10]:
df.info()

In [23]:
df.isnull().sum()

In [20]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [22]:
df.isnull().sum()

In [ ]:
# Loc and ILoc
# df.loc[row_range, column_name] --> start value include and last value include
# df.iloc[row_range, column_range] ---? start value include but last value exclude

In [ ]:
df.loc[5:10]

In [29]:
df.loc[5:10, ['age', 'fever', 'cough']]

In [32]:
df.iloc[5:10, [0,1,2,3]]

In [33]:
df.iloc[5:10, [0,2]] = 55


In [35]:
df.head(11)

In [36]:
df['gender'].value_counts()  ## subcatagory ka count nikalata hai

gender
Female    59
Male      41
Name: count, dtype: int64

In [37]:
df.head(2)

age gender  fever cough     city has_covid  Fever
0   60   Male  103.0  Mild  Kolkata        No  103.0
1   27   Male  100.0  Mild    Delhi       Yes  100.0

In [38]:
df['gender'] = df['gender'].map({'Male':0, 'Female':1})
df['cough'] = df['cough'].map({'Mild':0, 'Strong':1})


In [44]:
df['has_covid'] = df['has_covid'].map({'Yes':1 , 'No':0})

In [45]:
df.sample(3)

age  gender  fever  cough     city  has_covid  Fever
51   11       1  100.0      1  Kolkata          1  100.0
37   55       0  100.0      0  Kolkata          0  100.0
70   68       1  101.0      1    Delhi          0  101.0

In [48]:
df.drop(columns=['city']) ## original table(data) not effected

In [49]:
df = df.drop(columns=['city']) ## asign value original data change


In [51]:
df

In [52]:
df.head(2)

age  gender  fever  cough  has_covid  Fever
0   60       0  103.0      0          0  103.0
1   27       0  100.0      0          1  100.0

In [54]:
df.sort_index()  ## sort the data

In [57]:
df.rename(columns = {"cough":"updated_cough"}) ## not effect original data

In [58]:
df = df.rename(columns = {"cough":"updated_cough"}) ## effect original data


In [60]:
df

In [61]:
df['Age'] = df['age'].add(10)

In [ ]:
df.head(5)

In [63]:
df['fever'] = df['fever'].sub(100)

In [65]:
df.head(5)

In [66]:
df = df.drop(columns = ['Age'])

In [69]:
# df.head(2)

In [70]:
df[['age', 'fever']]  ## using this method, we can fillter the data

age  fever
0    60    3.0
1    27    0.0
2    42    1.0
3    31   -2.0
4    65    1.0
..  ...    ...
95   12    4.0
96   51    1.0
97   20    1.0
98    5   -2.0
99   10   -2.0

[100 rows x 2 columns]